---
- name: Run tasks on the local machine
  hosts: localhost
  become: true
  connection: local

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 360

    - name: Install htop
      apt:
        name: htop
        state: present
    
    - name: Install nginx
      apt:
        name: nginx
        state: present
      register: nginx_state

    - name: debug nginx_state
      debug: var=nginx_state

    - name: Create a hello world file
      copy:
        content: "Hello, Ansible was here!"
        dest: /tmp/ansible_test.txt
